main: org.golde.bukkit.corpsereborn.Main
name: CorpseReborn
authors: ["Eric Golde", "Peter Golde", "Virizion"]
website: https://www.spigotmc.org/resources/corpsereborn.29875/
version: 2.16.0 BETA
description: "Dead Bodies in Bukkit! Ported to 1.7.10-1.16.4 versions of Bukkit/Spigot/Paper. Thanks to Virizion for letting me take over and manage his old corpse plugin §4❤§f."
load: POSTWORLD
softdepend: [Multiverse-Core, MultiWorld, WorldGuard]
api-version: 1.13

commands:
  spawncorpse:
    usage: /<command> [Player]
    description: Spawn a corpse of a player!
    permission: corpses.spawn
    aliases: [spawnc, scorpse, sc]
  removecorpse:
    usage: /<command> [Radius]
    description: Remove a corpse of a player!
    permission: corpses.remove
    aliases: [removec, rcorpse, rc]
  corpsereborn:
    usage: /<command>
    description: Main info about plugin + reload config
    aliases: [cr, corpser, corpse, creborn]
  resendcorpses:
    usage: /<command>
    description: Resend corpses to all players
    permission: corpses.resend
    aliases: [resendc, cresend]
  togglecorpse:
    usage: /<command>
    description: Toggle if you see corpses or not
    permission: corpses.toggle
    aliases: [togglec, ctoggle, togglecorpses]
    
permissions:
  corpses.spawn:
    default: op
    description: Permission for /spawncorpse
  corpses.resend:
    default: op
    description: Permission for /resendcorpses
  corpses.remove:
    default: op
    description: Permission for /removecorpse
  corpses.reload:
    default: op
    description: Permission for /corpsereborn reload
  corpses.dump:
    default: op
    description: Permission for /corpsereborn dump
  corpses.toggle:
    default: op
    description: Permission for /togglecorpse